name: Mirror

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-cloud-runner
    permissions:
      contents: write

    steps:
      - name: Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Полная история коммитов

      - name: Git
        run: |
          git config --global user.name "x1z53"
          git config --global user.email "x1z53@корсаков.рус"

      - name: GitHub
        run: |
          git remote add target "https://x1z53:${{ secrets.GH_TOKEN }}@github.com/rus-yaz/korsakov"
          git push --mirror --force target
