name: Зеркалирование

on:
  push:
    branches:
      - "main"

jobs:
  mirror:
    runs-on: ubuntu-cloud-runner
    permissions:
      contents: write

    steps:
      - name: Код
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git
        run: |
          git config --global user.name "x1z53"
          git config --global user.email "x1z53@корсаков.рус"

      - name: GitHub
        run: |
          git remote add github "https://x1z53:${{ secrets.GH_TOKEN }}@github.com/rus-yaz/korsakov"
          git push --force --all github

      - name: Codeberg
        run: |
          git remote add codeberg "https://x1z53:${{ secrets.CB_TOKEN }}@codeberg.org/rus-yaz/korsakov"
          git push --force --all codeberg

      - name: GitLab
        run: |
          git remote add gitlab "https://x1z53:${{ secrets.GL_TOKEN }}@gitlab.com/rus.yaz/korsakov"
          git push --force --all gitlab

      - name: GitFlic
        run: |
          git remote add gitflic "https://x1z53:${{ secrets.GF_TOKEN }}@gitflic.ru/project/rus-yaz/korsakov.git"
          git push --force --all gitflic
