; Копирайт © 2025 ООО «РУС.ЯЗ»
; SPDX-License-Identifier: GPLv3+ ИЛИ прориетарная

include "arithmetical.asm"
include "boolean.asm"
include "comparisons.asm"
include "copy.asm"
include "delete.asm"
include "dictionary.asm"
include "exec.asm"
include "file.asm"
include "function.asm"
include "heap.asm"
include "exit.asm"
include "integer.asm"
include "float.asm"
include "list.asm"
include "null.asm"
include "print.asm"
include "error.asm"
include "string.asm"
include "to_string.asm"
include "variables.asm"
include "fs.asm"
include "random.asm"
include "input.asm"
include "math.asm"
